language: php

php:
    - 7.0
    - 5.6
    - 5.5

env:
    - COMPOSER_FLAGS=""
    - COMPOSER_FLAGS="--prefer-lowest"

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini

    - composer self-update

install:
    - composer update --prefer-dist $COMPOSER_FLAGS

script:
    - composer validate --strict

    - vendor/bin/phpspec run --no-interaction --format pretty
    - vendor/bin/phpunit --testdox
